# Generated by Django 4.0.6 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='articleContent',
            field=models.TextField(),
        ),
    ]
