# Generated by Django 4.2.5 on 2023-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataApp", "0002_alter_socialmedia_image_src_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="social_media",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
