# Generated by Django 4.2.5 on 2023-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataApp", "0003_alter_socialmedia_social_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="social_media",
            field=models.CharField(default="default-value", max_length=100),
        ),
    ]
