# Generated by Django 4.2.5 on 2023-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="newsArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sourceURL", models.CharField(max_length=100)),
                ("articleTitle", models.CharField(max_length=100)),
                ("articleContent", models.CharField(max_length=10000)),
                ("imageURL", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(default="Unverified", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="socialMediaPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sourceURL", models.CharField(max_length=100)),
                ("articleContent", models.CharField(max_length=10000)),
                ("imageURL", models.CharField(max_length=100, null=True)),
                ("platformName", models.CharField(max_length=20)),
                ("status", models.CharField(default="Unverified", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="userSelected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selectedContent", models.CharField(max_length=100)),
                ("confidence", models.IntegerField()),
                ("imageURL", models.CharField(max_length=100, null=True)),
                ("sourceURL", models.CharField(max_length=100)),
                ("proofURL", models.CharField(max_length=100)),
                ("userFeedback", models.CharField(max_length=100)),
                ("status", models.CharField(default="Unverified", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsappAndTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_content", models.TextField(null=True)),
                ("image_src", models.TextField(null=True)),
                ("social_media", models.CharField(max_length=30)),
                ("result", models.CharField(default="unverified", max_length=20)),
            ],
        ),
    ]
