# Generated by Django 4.0.6 on 2024-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_newsarticles_articlecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=100)),
                ('article_content', models.TextField(null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('platform_name', models.CharField(max_length=20)),
                ('status', models.CharField(default='Unverified', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='newsarticles',
            old_name='articleContent',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='newsarticles',
            old_name='articleTitle',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='newsarticles',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='newsarticles',
            old_name='sourceURL',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='socialmediaposts',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='socialmediaposts',
            old_name='platformName',
            new_name='platform_name',
        ),
        migrations.RenameField(
            model_name='socialmediaposts',
            old_name='sourceURL',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='userselected',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='userselected',
            old_name='proofURL',
            new_name='proof_url',
        ),
        migrations.RenameField(
            model_name='userselected',
            old_name='selectedContent',
            new_name='selected_content',
        ),
        migrations.RenameField(
            model_name='userselected',
            old_name='sourceURL',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='userselected',
            old_name='userFeedback',
            new_name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='socialmediaposts',
            name='articleContent',
        ),
        migrations.AddField(
            model_name='socialmediaposts',
            name='article_content',
            field=models.TextField(null=True),
        ),
    ]
